version: "3.4"
services:
    db:
        image: postgres
        container_name: home-t-database
        environment:
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
        restart: on-failure
        volumes:
            - ./.dbcache/postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: home-t-pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - 8080:80
        depends_on:
            - db
